name: lenga_edu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.6.5

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/branding/icon_cut.jpg"
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/simulations/
    - assets/branding/
    
